/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvinceSlugRouteImport } from './routes/province.$slug'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSubmitCompanyRouteImport } from './routes/_authenticated/dashboard.submit-company'
import { Route as AuthenticatedDashboardOwnerRouteImport } from './routes/_authenticated/dashboard.owner'
import { Route as AuthenticatedDashboardMyCompaniesRouteImport } from './routes/_authenticated/dashboard.my-companies'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as AuthenticatedDashboardBuyerRouteImport } from './routes/_authenticated/dashboard.buyer'
import { Route as AuthenticatedDashboardAuditLogRouteImport } from './routes/_authenticated/dashboard.audit-log'
import { Route as AuthenticatedDashboardArticlesRouteImport } from './routes/_authenticated/dashboard.articles'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as ApiPublicAdminLeadsRouteImport } from './routes/api/public/admin/leads'
import { Route as ApiPublicAdminCategoriesRouteImport } from './routes/api/public/admin/categories'
import { Route as ApiPublicAdminArticlesRouteImport } from './routes/api/public/admin/articles'
import { Route as AuthenticatedDashboardIntegrationsHermesRouteImport } from './routes/_authenticated/dashboard.integrations.hermes'
import { Route as AuthenticatedDashboardArticlesNewRouteImport } from './routes/_authenticated/dashboard.articles.new'
import { Route as ApiPublicAdminArticlesIdRouteImport } from './routes/api/public/admin/articles.$id'
import { Route as ApiPublicAdminAnalyticsSummaryRouteImport } from './routes/api/public/admin/analytics.summary'
import { Route as AuthenticatedDashboardArticlesIdEditRouteImport } from './routes/_authenticated/dashboard.articles.$id.edit'
import { Route as ApiPublicAdminArticlesIdPublishRouteImport } from './routes/api/public/admin/articles.$id.publish'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvinceSlugRoute = ProvinceSlugRouteImport.update({
  id: '/province/$slug',
  path: '/province/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSubmitCompanyRoute =
  AuthenticatedDashboardSubmitCompanyRouteImport.update({
    id: '/submit-company',
    path: '/submit-company',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOwnerRoute =
  AuthenticatedDashboardOwnerRouteImport.update({
    id: '/owner',
    path: '/owner',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyCompaniesRoute =
  AuthenticatedDashboardMyCompaniesRouteImport.update({
    id: '/my-companies',
    path: '/my-companies',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBuyerRoute =
  AuthenticatedDashboardBuyerRouteImport.update({
    id: '/buyer',
    path: '/buyer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAuditLogRoute =
  AuthenticatedDashboardAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardArticlesRoute =
  AuthenticatedDashboardArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicAdminLeadsRoute = ApiPublicAdminLeadsRouteImport.update({
  id: '/api/public/admin/leads',
  path: '/api/public/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminCategoriesRoute =
  ApiPublicAdminCategoriesRouteImport.update({
    id: '/api/public/admin/categories',
    path: '/api/public/admin/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminArticlesRoute = ApiPublicAdminArticlesRouteImport.update({
  id: '/api/public/admin/articles',
  path: '/api/public/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIntegrationsHermesRoute =
  AuthenticatedDashboardIntegrationsHermesRouteImport.update({
    id: '/integrations/hermes',
    path: '/integrations/hermes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardArticlesNewRoute =
  AuthenticatedDashboardArticlesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardArticlesRoute,
  } as any)
const ApiPublicAdminArticlesIdRoute =
  ApiPublicAdminArticlesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicAdminArticlesRoute,
  } as any)
const ApiPublicAdminAnalyticsSummaryRoute =
  ApiPublicAdminAnalyticsSummaryRouteImport.update({
    id: '/api/public/admin/analytics/summary',
    path: '/api/public/admin/analytics/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardArticlesIdEditRoute =
  AuthenticatedDashboardArticlesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedDashboardArticlesRoute,
  } as any)
const ApiPublicAdminArticlesIdPublishRoute =
  ApiPublicAdminArticlesIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiPublicAdminArticlesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/company/$slug': typeof CompanySlugRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/province/$slug': typeof ProvinceSlugRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/articles': typeof AuthenticatedDashboardArticlesRouteWithChildren
  '/dashboard/audit-log': typeof AuthenticatedDashboardAuditLogRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/my-companies': typeof AuthenticatedDashboardMyCompaniesRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/dashboard/submit-company': typeof AuthenticatedDashboardSubmitCompanyRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/dashboard/integrations/hermes': typeof AuthenticatedDashboardIntegrationsHermesRoute
  '/api/public/admin/articles': typeof ApiPublicAdminArticlesRouteWithChildren
  '/api/public/admin/categories': typeof ApiPublicAdminCategoriesRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
  '/api/public/admin/analytics/summary': typeof ApiPublicAdminAnalyticsSummaryRoute
  '/api/public/admin/articles/$id': typeof ApiPublicAdminArticlesIdRouteWithChildren
  '/api/public/admin/articles/$id/publish': typeof ApiPublicAdminArticlesIdPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/company/$slug': typeof CompanySlugRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/province/$slug': typeof ProvinceSlugRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/articles': typeof AuthenticatedDashboardArticlesRouteWithChildren
  '/dashboard/audit-log': typeof AuthenticatedDashboardAuditLogRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/my-companies': typeof AuthenticatedDashboardMyCompaniesRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/dashboard/submit-company': typeof AuthenticatedDashboardSubmitCompanyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/dashboard/integrations/hermes': typeof AuthenticatedDashboardIntegrationsHermesRoute
  '/api/public/admin/articles': typeof ApiPublicAdminArticlesRouteWithChildren
  '/api/public/admin/categories': typeof ApiPublicAdminCategoriesRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
  '/api/public/admin/analytics/summary': typeof ApiPublicAdminAnalyticsSummaryRoute
  '/api/public/admin/articles/$id': typeof ApiPublicAdminArticlesIdRouteWithChildren
  '/api/public/admin/articles/$id/publish': typeof ApiPublicAdminArticlesIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/company/$slug': typeof CompanySlugRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/province/$slug': typeof ProvinceSlugRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/articles': typeof AuthenticatedDashboardArticlesRouteWithChildren
  '/_authenticated/dashboard/audit-log': typeof AuthenticatedDashboardAuditLogRoute
  '/_authenticated/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/my-companies': typeof AuthenticatedDashboardMyCompaniesRoute
  '/_authenticated/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/_authenticated/dashboard/submit-company': typeof AuthenticatedDashboardSubmitCompanyRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/_authenticated/dashboard/integrations/hermes': typeof AuthenticatedDashboardIntegrationsHermesRoute
  '/api/public/admin/articles': typeof ApiPublicAdminArticlesRouteWithChildren
  '/api/public/admin/categories': typeof ApiPublicAdminCategoriesRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/_authenticated/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
  '/api/public/admin/analytics/summary': typeof ApiPublicAdminAnalyticsSummaryRoute
  '/api/public/admin/articles/$id': typeof ApiPublicAdminArticlesIdRouteWithChildren
  '/api/public/admin/articles/$id/publish': typeof ApiPublicAdminArticlesIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/admin'
    | '/dashboard'
    | '/company/$slug'
    | '/industry/$slug'
    | '/province/$slug'
    | '/dashboard/analytics'
    | '/dashboard/articles'
    | '/dashboard/audit-log'
    | '/dashboard/buyer'
    | '/dashboard/categories'
    | '/dashboard/leads'
    | '/dashboard/my-companies'
    | '/dashboard/owner'
    | '/dashboard/submit-company'
    | '/dashboard/'
    | '/dashboard/articles/new'
    | '/dashboard/integrations/hermes'
    | '/api/public/admin/articles'
    | '/api/public/admin/categories'
    | '/api/public/admin/leads'
    | '/dashboard/articles/$id/edit'
    | '/api/public/admin/analytics/summary'
    | '/api/public/admin/articles/$id'
    | '/api/public/admin/articles/$id/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/admin'
    | '/company/$slug'
    | '/industry/$slug'
    | '/province/$slug'
    | '/dashboard/analytics'
    | '/dashboard/articles'
    | '/dashboard/audit-log'
    | '/dashboard/buyer'
    | '/dashboard/categories'
    | '/dashboard/leads'
    | '/dashboard/my-companies'
    | '/dashboard/owner'
    | '/dashboard/submit-company'
    | '/dashboard'
    | '/dashboard/articles/new'
    | '/dashboard/integrations/hermes'
    | '/api/public/admin/articles'
    | '/api/public/admin/categories'
    | '/api/public/admin/leads'
    | '/dashboard/articles/$id/edit'
    | '/api/public/admin/analytics/summary'
    | '/api/public/admin/articles/$id'
    | '/api/public/admin/articles/$id/publish'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/company/$slug'
    | '/industry/$slug'
    | '/province/$slug'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/articles'
    | '/_authenticated/dashboard/audit-log'
    | '/_authenticated/dashboard/buyer'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/my-companies'
    | '/_authenticated/dashboard/owner'
    | '/_authenticated/dashboard/submit-company'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/articles/new'
    | '/_authenticated/dashboard/integrations/hermes'
    | '/api/public/admin/articles'
    | '/api/public/admin/categories'
    | '/api/public/admin/leads'
    | '/_authenticated/dashboard/articles/$id/edit'
    | '/api/public/admin/analytics/summary'
    | '/api/public/admin/articles/$id'
    | '/api/public/admin/articles/$id/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CompanySlugRoute: typeof CompanySlugRoute
  IndustrySlugRoute: typeof IndustrySlugRoute
  ProvinceSlugRoute: typeof ProvinceSlugRoute
  ApiPublicAdminArticlesRoute: typeof ApiPublicAdminArticlesRouteWithChildren
  ApiPublicAdminCategoriesRoute: typeof ApiPublicAdminCategoriesRoute
  ApiPublicAdminLeadsRoute: typeof ApiPublicAdminLeadsRoute
  ApiPublicAdminAnalyticsSummaryRoute: typeof ApiPublicAdminAnalyticsSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/province/$slug': {
      id: '/province/$slug'
      path: '/province/$slug'
      fullPath: '/province/$slug'
      preLoaderRoute: typeof ProvinceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/submit-company': {
      id: '/_authenticated/dashboard/submit-company'
      path: '/submit-company'
      fullPath: '/dashboard/submit-company'
      preLoaderRoute: typeof AuthenticatedDashboardSubmitCompanyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/owner': {
      id: '/_authenticated/dashboard/owner'
      path: '/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof AuthenticatedDashboardOwnerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-companies': {
      id: '/_authenticated/dashboard/my-companies'
      path: '/my-companies'
      fullPath: '/dashboard/my-companies'
      preLoaderRoute: typeof AuthenticatedDashboardMyCompaniesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/buyer': {
      id: '/_authenticated/dashboard/buyer'
      path: '/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof AuthenticatedDashboardBuyerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/audit-log': {
      id: '/_authenticated/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof AuthenticatedDashboardAuditLogRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/articles': {
      id: '/_authenticated/dashboard/articles'
      path: '/articles'
      fullPath: '/dashboard/articles'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/admin/leads': {
      id: '/api/public/admin/leads'
      path: '/api/public/admin/leads'
      fullPath: '/api/public/admin/leads'
      preLoaderRoute: typeof ApiPublicAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/categories': {
      id: '/api/public/admin/categories'
      path: '/api/public/admin/categories'
      fullPath: '/api/public/admin/categories'
      preLoaderRoute: typeof ApiPublicAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/articles': {
      id: '/api/public/admin/articles'
      path: '/api/public/admin/articles'
      fullPath: '/api/public/admin/articles'
      preLoaderRoute: typeof ApiPublicAdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/integrations/hermes': {
      id: '/_authenticated/dashboard/integrations/hermes'
      path: '/integrations/hermes'
      fullPath: '/dashboard/integrations/hermes'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsHermesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/articles/new': {
      id: '/_authenticated/dashboard/articles/new'
      path: '/new'
      fullPath: '/dashboard/articles/new'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardArticlesRoute
    }
    '/api/public/admin/articles/$id': {
      id: '/api/public/admin/articles/$id'
      path: '/$id'
      fullPath: '/api/public/admin/articles/$id'
      preLoaderRoute: typeof ApiPublicAdminArticlesIdRouteImport
      parentRoute: typeof ApiPublicAdminArticlesRoute
    }
    '/api/public/admin/analytics/summary': {
      id: '/api/public/admin/analytics/summary'
      path: '/api/public/admin/analytics/summary'
      fullPath: '/api/public/admin/analytics/summary'
      preLoaderRoute: typeof ApiPublicAdminAnalyticsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/articles/$id/edit': {
      id: '/_authenticated/dashboard/articles/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/articles/$id/edit'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardArticlesRoute
    }
    '/api/public/admin/articles/$id/publish': {
      id: '/api/public/admin/articles/$id/publish'
      path: '/publish'
      fullPath: '/api/public/admin/articles/$id/publish'
      preLoaderRoute: typeof ApiPublicAdminArticlesIdPublishRouteImport
      parentRoute: typeof ApiPublicAdminArticlesIdRoute
    }
  }
}

interface AuthenticatedDashboardArticlesRouteChildren {
  AuthenticatedDashboardArticlesNewRoute: typeof AuthenticatedDashboardArticlesNewRoute
  AuthenticatedDashboardArticlesIdEditRoute: typeof AuthenticatedDashboardArticlesIdEditRoute
}

const AuthenticatedDashboardArticlesRouteChildren: AuthenticatedDashboardArticlesRouteChildren =
  {
    AuthenticatedDashboardArticlesNewRoute:
      AuthenticatedDashboardArticlesNewRoute,
    AuthenticatedDashboardArticlesIdEditRoute:
      AuthenticatedDashboardArticlesIdEditRoute,
  }

const AuthenticatedDashboardArticlesRouteWithChildren =
  AuthenticatedDashboardArticlesRoute._addFileChildren(
    AuthenticatedDashboardArticlesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardArticlesRoute: typeof AuthenticatedDashboardArticlesRouteWithChildren
  AuthenticatedDashboardAuditLogRoute: typeof AuthenticatedDashboardAuditLogRoute
  AuthenticatedDashboardBuyerRoute: typeof AuthenticatedDashboardBuyerRoute
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardMyCompaniesRoute: typeof AuthenticatedDashboardMyCompaniesRoute
  AuthenticatedDashboardOwnerRoute: typeof AuthenticatedDashboardOwnerRoute
  AuthenticatedDashboardSubmitCompanyRoute: typeof AuthenticatedDashboardSubmitCompanyRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardIntegrationsHermesRoute: typeof AuthenticatedDashboardIntegrationsHermesRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardArticlesRoute:
      AuthenticatedDashboardArticlesRouteWithChildren,
    AuthenticatedDashboardAuditLogRoute: AuthenticatedDashboardAuditLogRoute,
    AuthenticatedDashboardBuyerRoute: AuthenticatedDashboardBuyerRoute,
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardMyCompaniesRoute:
      AuthenticatedDashboardMyCompaniesRoute,
    AuthenticatedDashboardOwnerRoute: AuthenticatedDashboardOwnerRoute,
    AuthenticatedDashboardSubmitCompanyRoute:
      AuthenticatedDashboardSubmitCompanyRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardIntegrationsHermesRoute:
      AuthenticatedDashboardIntegrationsHermesRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicAdminArticlesIdRouteChildren {
  ApiPublicAdminArticlesIdPublishRoute: typeof ApiPublicAdminArticlesIdPublishRoute
}

const ApiPublicAdminArticlesIdRouteChildren: ApiPublicAdminArticlesIdRouteChildren =
  {
    ApiPublicAdminArticlesIdPublishRoute: ApiPublicAdminArticlesIdPublishRoute,
  }

const ApiPublicAdminArticlesIdRouteWithChildren =
  ApiPublicAdminArticlesIdRoute._addFileChildren(
    ApiPublicAdminArticlesIdRouteChildren,
  )

interface ApiPublicAdminArticlesRouteChildren {
  ApiPublicAdminArticlesIdRoute: typeof ApiPublicAdminArticlesIdRouteWithChildren
}

const ApiPublicAdminArticlesRouteChildren: ApiPublicAdminArticlesRouteChildren =
  {
    ApiPublicAdminArticlesIdRoute: ApiPublicAdminArticlesIdRouteWithChildren,
  }

const ApiPublicAdminArticlesRouteWithChildren =
  ApiPublicAdminArticlesRoute._addFileChildren(
    ApiPublicAdminArticlesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CompanySlugRoute: CompanySlugRoute,
  IndustrySlugRoute: IndustrySlugRoute,
  ProvinceSlugRoute: ProvinceSlugRoute,
  ApiPublicAdminArticlesRoute: ApiPublicAdminArticlesRouteWithChildren,
  ApiPublicAdminCategoriesRoute: ApiPublicAdminCategoriesRoute,
  ApiPublicAdminLeadsRoute: ApiPublicAdminLeadsRoute,
  ApiPublicAdminAnalyticsSummaryRoute: ApiPublicAdminAnalyticsSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
