/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapZonesDotxmlRouteImport } from './routes/sitemap-zones[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SitemapProvincesDotxmlRouteImport } from './routes/sitemap-provinces[.]xml'
import { Route as SitemapIndustriesDotxmlRouteImport } from './routes/sitemap-industries[.]xml'
import { Route as SitemapCompaniesDotxmlRouteImport } from './routes/sitemap-companies[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KhuCongNghiepIndexRouteImport } from './routes/khu-cong-nghiep.index'
import { Route as KcnCcnIndexRouteImport } from './routes/kcn-ccn.index'
import { Route as CumCongNghiepIndexRouteImport } from './routes/cum-cong-nghiep.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProvinceSlugRouteImport } from './routes/province.$slug'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as KhuCongNghiepSlugRouteImport } from './routes/khu-cong-nghiep.$slug'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as CumCongNghiepSlugRouteImport } from './routes/cum-cong-nghiep.$slug'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSubscriptionsRouteImport } from './routes/_authenticated/dashboard.subscriptions'
import { Route as AuthenticatedDashboardSubmitCompanyRouteImport } from './routes/_authenticated/dashboard.submit-company'
import { Route as AuthenticatedDashboardOwnerRouteImport } from './routes/_authenticated/dashboard.owner'
import { Route as AuthenticatedDashboardMyCompaniesRouteImport } from './routes/_authenticated/dashboard.my-companies'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as AuthenticatedDashboardBuyerRouteImport } from './routes/_authenticated/dashboard.buyer'
import { Route as AuthenticatedDashboardAuditLogRouteImport } from './routes/_authenticated/dashboard.audit-log'
import { Route as AuthenticatedDashboardAuctionRouteImport } from './routes/_authenticated/dashboard.auction'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardArticlesIndexRouteImport } from './routes/_authenticated/dashboard.articles.index'
import { Route as ApiPublicWebhooksPayosRouteImport } from './routes/api/public/webhooks/payos'
import { Route as ApiPublicHooksPriorityRecalculateRouteImport } from './routes/api/public/hooks/priority-recalculate'
import { Route as ApiPublicHooksExpireSubscriptionsRouteImport } from './routes/api/public/hooks/expire-subscriptions'
import { Route as ApiPublicAdminLeadsRouteImport } from './routes/api/public/admin/leads'
import { Route as ApiPublicAdminCategoriesRouteImport } from './routes/api/public/admin/categories'
import { Route as ApiPublicAdminArticlesRouteImport } from './routes/api/public/admin/articles'
import { Route as AuthenticatedDashboardIntegrationsHermesRouteImport } from './routes/_authenticated/dashboard.integrations.hermes'
import { Route as AuthenticatedDashboardArticlesNewRouteImport } from './routes/_authenticated/dashboard.articles.new'
import { Route as AuthenticatedDashboardAdminZonesRouteImport } from './routes/_authenticated/dashboard.admin.zones'
import { Route as AuthenticatedDashboardAdminImportRouteImport } from './routes/_authenticated/dashboard.admin.import'
import { Route as AuthenticatedDashboardAdminEditRouteImport } from './routes/_authenticated/dashboard.admin.edit'
import { Route as AuthenticatedDashboardAdminCompaniesRouteImport } from './routes/_authenticated/dashboard.admin.companies'
import { Route as AuthenticatedDashboardAdminClaimsRouteImport } from './routes/_authenticated/dashboard.admin.claims'
import { Route as ApiPublicAdminCompaniesBatchRouteImport } from './routes/api/public/admin/companies.batch'
import { Route as ApiPublicAdminArticlesIdRouteImport } from './routes/api/public/admin/articles.$id'
import { Route as ApiPublicAdminAnalyticsSummaryRouteImport } from './routes/api/public/admin/analytics.summary'
import { Route as AuthenticatedDashboardArticlesIdEditRouteImport } from './routes/_authenticated/dashboard.articles.$id.edit'
import { Route as ApiPublicAdminArticlesIdPublishRouteImport } from './routes/api/public/admin/articles.$id.publish'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapZonesDotxmlRoute = SitemapZonesDotxmlRouteImport.update({
  id: '/sitemap-zones.xml',
  path: '/sitemap-zones.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProvincesDotxmlRoute = SitemapProvincesDotxmlRouteImport.update({
  id: '/sitemap-provinces.xml',
  path: '/sitemap-provinces.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndustriesDotxmlRoute = SitemapIndustriesDotxmlRouteImport.update({
  id: '/sitemap-industries.xml',
  path: '/sitemap-industries.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCompaniesDotxmlRoute = SitemapCompaniesDotxmlRouteImport.update({
  id: '/sitemap-companies.xml',
  path: '/sitemap-companies.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuCongNghiepIndexRoute = KhuCongNghiepIndexRouteImport.update({
  id: '/khu-cong-nghiep/',
  path: '/khu-cong-nghiep/',
  getParentRoute: () => rootRouteImport,
} as any)
const KcnCcnIndexRoute = KcnCcnIndexRouteImport.update({
  id: '/kcn-ccn/',
  path: '/kcn-ccn/',
  getParentRoute: () => rootRouteImport,
} as any)
const CumCongNghiepIndexRoute = CumCongNghiepIndexRouteImport.update({
  id: '/cum-cong-nghiep/',
  path: '/cum-cong-nghiep/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvinceSlugRoute = ProvinceSlugRouteImport.update({
  id: '/province/$slug',
  path: '/province/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuCongNghiepSlugRoute = KhuCongNghiepSlugRouteImport.update({
  id: '/khu-cong-nghiep/$slug',
  path: '/khu-cong-nghiep/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CumCongNghiepSlugRoute = CumCongNghiepSlugRouteImport.update({
  id: '/cum-cong-nghiep/$slug',
  path: '/cum-cong-nghiep/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSubscriptionsRoute =
  AuthenticatedDashboardSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSubmitCompanyRoute =
  AuthenticatedDashboardSubmitCompanyRouteImport.update({
    id: '/submit-company',
    path: '/submit-company',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOwnerRoute =
  AuthenticatedDashboardOwnerRouteImport.update({
    id: '/owner',
    path: '/owner',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyCompaniesRoute =
  AuthenticatedDashboardMyCompaniesRouteImport.update({
    id: '/my-companies',
    path: '/my-companies',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBuyerRoute =
  AuthenticatedDashboardBuyerRouteImport.update({
    id: '/buyer',
    path: '/buyer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAuditLogRoute =
  AuthenticatedDashboardAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAuctionRoute =
  AuthenticatedDashboardAuctionRouteImport.update({
    id: '/auction',
    path: '/auction',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardArticlesIndexRoute =
  AuthenticatedDashboardArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicWebhooksPayosRoute = ApiPublicWebhooksPayosRouteImport.update({
  id: '/public/webhooks/payos',
  path: '/public/webhooks/payos',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicHooksPriorityRecalculateRoute =
  ApiPublicHooksPriorityRecalculateRouteImport.update({
    id: '/public/hooks/priority-recalculate',
    path: '/public/hooks/priority-recalculate',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicHooksExpireSubscriptionsRoute =
  ApiPublicHooksExpireSubscriptionsRouteImport.update({
    id: '/public/hooks/expire-subscriptions',
    path: '/public/hooks/expire-subscriptions',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicAdminLeadsRoute = ApiPublicAdminLeadsRouteImport.update({
  id: '/public/admin/leads',
  path: '/public/admin/leads',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicAdminCategoriesRoute =
  ApiPublicAdminCategoriesRouteImport.update({
    id: '/public/admin/categories',
    path: '/public/admin/categories',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicAdminArticlesRoute = ApiPublicAdminArticlesRouteImport.update({
  id: '/public/admin/articles',
  path: '/public/admin/articles',
  getParentRoute: () => ApiRoute,
} as any)
const AuthenticatedDashboardIntegrationsHermesRoute =
  AuthenticatedDashboardIntegrationsHermesRouteImport.update({
    id: '/integrations/hermes',
    path: '/integrations/hermes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardArticlesNewRoute =
  AuthenticatedDashboardArticlesNewRouteImport.update({
    id: '/articles/new',
    path: '/articles/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminZonesRoute =
  AuthenticatedDashboardAdminZonesRouteImport.update({
    id: '/admin/zones',
    path: '/admin/zones',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminImportRoute =
  AuthenticatedDashboardAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminEditRoute =
  AuthenticatedDashboardAdminEditRouteImport.update({
    id: '/admin/edit',
    path: '/admin/edit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminCompaniesRoute =
  AuthenticatedDashboardAdminCompaniesRouteImport.update({
    id: '/admin/companies',
    path: '/admin/companies',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminClaimsRoute =
  AuthenticatedDashboardAdminClaimsRouteImport.update({
    id: '/admin/claims',
    path: '/admin/claims',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicAdminCompaniesBatchRoute =
  ApiPublicAdminCompaniesBatchRouteImport.update({
    id: '/public/admin/companies/batch',
    path: '/public/admin/companies/batch',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicAdminArticlesIdRoute =
  ApiPublicAdminArticlesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicAdminArticlesRoute,
  } as any)
const ApiPublicAdminAnalyticsSummaryRoute =
  ApiPublicAdminAnalyticsSummaryRouteImport.update({
    id: '/public/admin/analytics/summary',
    path: '/public/admin/analytics/summary',
    getParentRoute: () => ApiRoute,
  } as any)
const AuthenticatedDashboardArticlesIdEditRoute =
  AuthenticatedDashboardArticlesIdEditRouteImport.update({
    id: '/articles/$id/edit',
    path: '/articles/$id/edit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicAdminArticlesIdPublishRoute =
  ApiPublicAdminArticlesIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiPublicAdminArticlesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap-companies.xml': typeof SitemapCompaniesDotxmlRoute
  '/sitemap-industries.xml': typeof SitemapIndustriesDotxmlRoute
  '/sitemap-provinces.xml': typeof SitemapProvincesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap-zones.xml': typeof SitemapZonesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/cum-cong-nghiep/$slug': typeof CumCongNghiepSlugRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/khu-cong-nghiep/$slug': typeof KhuCongNghiepSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/province/$slug': typeof ProvinceSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/cum-cong-nghiep/': typeof CumCongNghiepIndexRoute
  '/kcn-ccn/': typeof KcnCcnIndexRoute
  '/khu-cong-nghiep/': typeof KhuCongNghiepIndexRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/auction': typeof AuthenticatedDashboardAuctionRoute
  '/dashboard/audit-log': typeof AuthenticatedDashboardAuditLogRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/my-companies': typeof AuthenticatedDashboardMyCompaniesRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/dashboard/submit-company': typeof AuthenticatedDashboardSubmitCompanyRoute
  '/dashboard/subscriptions': typeof AuthenticatedDashboardSubscriptionsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/claims': typeof AuthenticatedDashboardAdminClaimsRoute
  '/dashboard/admin/companies': typeof AuthenticatedDashboardAdminCompaniesRoute
  '/dashboard/admin/edit': typeof AuthenticatedDashboardAdminEditRoute
  '/dashboard/admin/import': typeof AuthenticatedDashboardAdminImportRoute
  '/dashboard/admin/zones': typeof AuthenticatedDashboardAdminZonesRoute
  '/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/dashboard/integrations/hermes': typeof AuthenticatedDashboardIntegrationsHermesRoute
  '/api/public/admin/articles': typeof ApiPublicAdminArticlesRouteWithChildren
  '/api/public/admin/categories': typeof ApiPublicAdminCategoriesRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/api/public/hooks/expire-subscriptions': typeof ApiPublicHooksExpireSubscriptionsRoute
  '/api/public/hooks/priority-recalculate': typeof ApiPublicHooksPriorityRecalculateRoute
  '/api/public/webhooks/payos': typeof ApiPublicWebhooksPayosRoute
  '/dashboard/articles/': typeof AuthenticatedDashboardArticlesIndexRoute
  '/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
  '/api/public/admin/analytics/summary': typeof ApiPublicAdminAnalyticsSummaryRoute
  '/api/public/admin/articles/$id': typeof ApiPublicAdminArticlesIdRouteWithChildren
  '/api/public/admin/companies/batch': typeof ApiPublicAdminCompaniesBatchRoute
  '/api/public/admin/articles/$id/publish': typeof ApiPublicAdminArticlesIdPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap-companies.xml': typeof SitemapCompaniesDotxmlRoute
  '/sitemap-industries.xml': typeof SitemapIndustriesDotxmlRoute
  '/sitemap-provinces.xml': typeof SitemapProvincesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap-zones.xml': typeof SitemapZonesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/cum-cong-nghiep/$slug': typeof CumCongNghiepSlugRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/khu-cong-nghiep/$slug': typeof KhuCongNghiepSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/province/$slug': typeof ProvinceSlugRoute
  '/blog': typeof BlogIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/cum-cong-nghiep': typeof CumCongNghiepIndexRoute
  '/kcn-ccn': typeof KcnCcnIndexRoute
  '/khu-cong-nghiep': typeof KhuCongNghiepIndexRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/auction': typeof AuthenticatedDashboardAuctionRoute
  '/dashboard/audit-log': typeof AuthenticatedDashboardAuditLogRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/my-companies': typeof AuthenticatedDashboardMyCompaniesRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/dashboard/submit-company': typeof AuthenticatedDashboardSubmitCompanyRoute
  '/dashboard/subscriptions': typeof AuthenticatedDashboardSubscriptionsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/claims': typeof AuthenticatedDashboardAdminClaimsRoute
  '/dashboard/admin/companies': typeof AuthenticatedDashboardAdminCompaniesRoute
  '/dashboard/admin/edit': typeof AuthenticatedDashboardAdminEditRoute
  '/dashboard/admin/import': typeof AuthenticatedDashboardAdminImportRoute
  '/dashboard/admin/zones': typeof AuthenticatedDashboardAdminZonesRoute
  '/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/dashboard/integrations/hermes': typeof AuthenticatedDashboardIntegrationsHermesRoute
  '/api/public/admin/articles': typeof ApiPublicAdminArticlesRouteWithChildren
  '/api/public/admin/categories': typeof ApiPublicAdminCategoriesRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/api/public/hooks/expire-subscriptions': typeof ApiPublicHooksExpireSubscriptionsRoute
  '/api/public/hooks/priority-recalculate': typeof ApiPublicHooksPriorityRecalculateRoute
  '/api/public/webhooks/payos': typeof ApiPublicWebhooksPayosRoute
  '/dashboard/articles': typeof AuthenticatedDashboardArticlesIndexRoute
  '/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
  '/api/public/admin/analytics/summary': typeof ApiPublicAdminAnalyticsSummaryRoute
  '/api/public/admin/articles/$id': typeof ApiPublicAdminArticlesIdRouteWithChildren
  '/api/public/admin/companies/batch': typeof ApiPublicAdminCompaniesBatchRoute
  '/api/public/admin/articles/$id/publish': typeof ApiPublicAdminArticlesIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap-companies.xml': typeof SitemapCompaniesDotxmlRoute
  '/sitemap-industries.xml': typeof SitemapIndustriesDotxmlRoute
  '/sitemap-provinces.xml': typeof SitemapProvincesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap-zones.xml': typeof SitemapZonesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/company/$slug': typeof CompanySlugRoute
  '/cum-cong-nghiep/$slug': typeof CumCongNghiepSlugRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/khu-cong-nghiep/$slug': typeof KhuCongNghiepSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/province/$slug': typeof ProvinceSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/cum-cong-nghiep/': typeof CumCongNghiepIndexRoute
  '/kcn-ccn/': typeof KcnCcnIndexRoute
  '/khu-cong-nghiep/': typeof KhuCongNghiepIndexRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/auction': typeof AuthenticatedDashboardAuctionRoute
  '/_authenticated/dashboard/audit-log': typeof AuthenticatedDashboardAuditLogRoute
  '/_authenticated/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/my-companies': typeof AuthenticatedDashboardMyCompaniesRoute
  '/_authenticated/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/_authenticated/dashboard/submit-company': typeof AuthenticatedDashboardSubmitCompanyRoute
  '/_authenticated/dashboard/subscriptions': typeof AuthenticatedDashboardSubscriptionsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/claims': typeof AuthenticatedDashboardAdminClaimsRoute
  '/_authenticated/dashboard/admin/companies': typeof AuthenticatedDashboardAdminCompaniesRoute
  '/_authenticated/dashboard/admin/edit': typeof AuthenticatedDashboardAdminEditRoute
  '/_authenticated/dashboard/admin/import': typeof AuthenticatedDashboardAdminImportRoute
  '/_authenticated/dashboard/admin/zones': typeof AuthenticatedDashboardAdminZonesRoute
  '/_authenticated/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/_authenticated/dashboard/integrations/hermes': typeof AuthenticatedDashboardIntegrationsHermesRoute
  '/api/public/admin/articles': typeof ApiPublicAdminArticlesRouteWithChildren
  '/api/public/admin/categories': typeof ApiPublicAdminCategoriesRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/api/public/hooks/expire-subscriptions': typeof ApiPublicHooksExpireSubscriptionsRoute
  '/api/public/hooks/priority-recalculate': typeof ApiPublicHooksPriorityRecalculateRoute
  '/api/public/webhooks/payos': typeof ApiPublicWebhooksPayosRoute
  '/_authenticated/dashboard/articles/': typeof AuthenticatedDashboardArticlesIndexRoute
  '/_authenticated/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
  '/api/public/admin/analytics/summary': typeof ApiPublicAdminAnalyticsSummaryRoute
  '/api/public/admin/articles/$id': typeof ApiPublicAdminArticlesIdRouteWithChildren
  '/api/public/admin/companies/batch': typeof ApiPublicAdminCompaniesBatchRoute
  '/api/public/admin/articles/$id/publish': typeof ApiPublicAdminArticlesIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/sitemap-companies.xml'
    | '/sitemap-industries.xml'
    | '/sitemap-provinces.xml'
    | '/sitemap-static.xml'
    | '/sitemap-zones.xml'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/dashboard'
    | '/blog/$slug'
    | '/company/$slug'
    | '/cum-cong-nghiep/$slug'
    | '/industry/$slug'
    | '/khu-cong-nghiep/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/province/$slug'
    | '/blog/'
    | '/companies/'
    | '/cum-cong-nghiep/'
    | '/kcn-ccn/'
    | '/khu-cong-nghiep/'
    | '/dashboard/analytics'
    | '/dashboard/auction'
    | '/dashboard/audit-log'
    | '/dashboard/buyer'
    | '/dashboard/categories'
    | '/dashboard/leads'
    | '/dashboard/my-companies'
    | '/dashboard/owner'
    | '/dashboard/submit-company'
    | '/dashboard/subscriptions'
    | '/dashboard/'
    | '/dashboard/admin/claims'
    | '/dashboard/admin/companies'
    | '/dashboard/admin/edit'
    | '/dashboard/admin/import'
    | '/dashboard/admin/zones'
    | '/dashboard/articles/new'
    | '/dashboard/integrations/hermes'
    | '/api/public/admin/articles'
    | '/api/public/admin/categories'
    | '/api/public/admin/leads'
    | '/api/public/hooks/expire-subscriptions'
    | '/api/public/hooks/priority-recalculate'
    | '/api/public/webhooks/payos'
    | '/dashboard/articles/'
    | '/dashboard/articles/$id/edit'
    | '/api/public/admin/analytics/summary'
    | '/api/public/admin/articles/$id'
    | '/api/public/admin/companies/batch'
    | '/api/public/admin/articles/$id/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/sitemap-companies.xml'
    | '/sitemap-industries.xml'
    | '/sitemap-provinces.xml'
    | '/sitemap-static.xml'
    | '/sitemap-zones.xml'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/blog/$slug'
    | '/company/$slug'
    | '/cum-cong-nghiep/$slug'
    | '/industry/$slug'
    | '/khu-cong-nghiep/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/province/$slug'
    | '/blog'
    | '/companies'
    | '/cum-cong-nghiep'
    | '/kcn-ccn'
    | '/khu-cong-nghiep'
    | '/dashboard/analytics'
    | '/dashboard/auction'
    | '/dashboard/audit-log'
    | '/dashboard/buyer'
    | '/dashboard/categories'
    | '/dashboard/leads'
    | '/dashboard/my-companies'
    | '/dashboard/owner'
    | '/dashboard/submit-company'
    | '/dashboard/subscriptions'
    | '/dashboard'
    | '/dashboard/admin/claims'
    | '/dashboard/admin/companies'
    | '/dashboard/admin/edit'
    | '/dashboard/admin/import'
    | '/dashboard/admin/zones'
    | '/dashboard/articles/new'
    | '/dashboard/integrations/hermes'
    | '/api/public/admin/articles'
    | '/api/public/admin/categories'
    | '/api/public/admin/leads'
    | '/api/public/hooks/expire-subscriptions'
    | '/api/public/hooks/priority-recalculate'
    | '/api/public/webhooks/payos'
    | '/dashboard/articles'
    | '/dashboard/articles/$id/edit'
    | '/api/public/admin/analytics/summary'
    | '/api/public/admin/articles/$id'
    | '/api/public/admin/companies/batch'
    | '/api/public/admin/articles/$id/publish'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/api'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/sitemap-companies.xml'
    | '/sitemap-industries.xml'
    | '/sitemap-provinces.xml'
    | '/sitemap-static.xml'
    | '/sitemap-zones.xml'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/company/$slug'
    | '/cum-cong-nghiep/$slug'
    | '/industry/$slug'
    | '/khu-cong-nghiep/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/province/$slug'
    | '/blog/'
    | '/companies/'
    | '/cum-cong-nghiep/'
    | '/kcn-ccn/'
    | '/khu-cong-nghiep/'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/auction'
    | '/_authenticated/dashboard/audit-log'
    | '/_authenticated/dashboard/buyer'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/my-companies'
    | '/_authenticated/dashboard/owner'
    | '/_authenticated/dashboard/submit-company'
    | '/_authenticated/dashboard/subscriptions'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/claims'
    | '/_authenticated/dashboard/admin/companies'
    | '/_authenticated/dashboard/admin/edit'
    | '/_authenticated/dashboard/admin/import'
    | '/_authenticated/dashboard/admin/zones'
    | '/_authenticated/dashboard/articles/new'
    | '/_authenticated/dashboard/integrations/hermes'
    | '/api/public/admin/articles'
    | '/api/public/admin/categories'
    | '/api/public/admin/leads'
    | '/api/public/hooks/expire-subscriptions'
    | '/api/public/hooks/priority-recalculate'
    | '/api/public/webhooks/payos'
    | '/_authenticated/dashboard/articles/'
    | '/_authenticated/dashboard/articles/$id/edit'
    | '/api/public/admin/analytics/summary'
    | '/api/public/admin/articles/$id'
    | '/api/public/admin/companies/batch'
    | '/api/public/admin/articles/$id/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiRoute: typeof ApiRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapCompaniesDotxmlRoute: typeof SitemapCompaniesDotxmlRoute
  SitemapIndustriesDotxmlRoute: typeof SitemapIndustriesDotxmlRoute
  SitemapProvincesDotxmlRoute: typeof SitemapProvincesDotxmlRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapZonesDotxmlRoute: typeof SitemapZonesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompanySlugRoute: typeof CompanySlugRoute
  CumCongNghiepSlugRoute: typeof CumCongNghiepSlugRoute
  IndustrySlugRoute: typeof IndustrySlugRoute
  KhuCongNghiepSlugRoute: typeof KhuCongNghiepSlugRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProvinceSlugRoute: typeof ProvinceSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  CumCongNghiepIndexRoute: typeof CumCongNghiepIndexRoute
  KcnCcnIndexRoute: typeof KcnCcnIndexRoute
  KhuCongNghiepIndexRoute: typeof KhuCongNghiepIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-zones.xml': {
      id: '/sitemap-zones.xml'
      path: '/sitemap-zones.xml'
      fullPath: '/sitemap-zones.xml'
      preLoaderRoute: typeof SitemapZonesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-provinces.xml': {
      id: '/sitemap-provinces.xml'
      path: '/sitemap-provinces.xml'
      fullPath: '/sitemap-provinces.xml'
      preLoaderRoute: typeof SitemapProvincesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-industries.xml': {
      id: '/sitemap-industries.xml'
      path: '/sitemap-industries.xml'
      fullPath: '/sitemap-industries.xml'
      preLoaderRoute: typeof SitemapIndustriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-companies.xml': {
      id: '/sitemap-companies.xml'
      path: '/sitemap-companies.xml'
      fullPath: '/sitemap-companies.xml'
      preLoaderRoute: typeof SitemapCompaniesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khu-cong-nghiep/': {
      id: '/khu-cong-nghiep/'
      path: '/khu-cong-nghiep'
      fullPath: '/khu-cong-nghiep/'
      preLoaderRoute: typeof KhuCongNghiepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kcn-ccn/': {
      id: '/kcn-ccn/'
      path: '/kcn-ccn'
      fullPath: '/kcn-ccn/'
      preLoaderRoute: typeof KcnCcnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cum-cong-nghiep/': {
      id: '/cum-cong-nghiep/'
      path: '/cum-cong-nghiep'
      fullPath: '/cum-cong-nghiep/'
      preLoaderRoute: typeof CumCongNghiepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/province/$slug': {
      id: '/province/$slug'
      path: '/province/$slug'
      fullPath: '/province/$slug'
      preLoaderRoute: typeof ProvinceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khu-cong-nghiep/$slug': {
      id: '/khu-cong-nghiep/$slug'
      path: '/khu-cong-nghiep/$slug'
      fullPath: '/khu-cong-nghiep/$slug'
      preLoaderRoute: typeof KhuCongNghiepSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cum-cong-nghiep/$slug': {
      id: '/cum-cong-nghiep/$slug'
      path: '/cum-cong-nghiep/$slug'
      fullPath: '/cum-cong-nghiep/$slug'
      preLoaderRoute: typeof CumCongNghiepSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/subscriptions': {
      id: '/_authenticated/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof AuthenticatedDashboardSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/submit-company': {
      id: '/_authenticated/dashboard/submit-company'
      path: '/submit-company'
      fullPath: '/dashboard/submit-company'
      preLoaderRoute: typeof AuthenticatedDashboardSubmitCompanyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/owner': {
      id: '/_authenticated/dashboard/owner'
      path: '/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof AuthenticatedDashboardOwnerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-companies': {
      id: '/_authenticated/dashboard/my-companies'
      path: '/my-companies'
      fullPath: '/dashboard/my-companies'
      preLoaderRoute: typeof AuthenticatedDashboardMyCompaniesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/buyer': {
      id: '/_authenticated/dashboard/buyer'
      path: '/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof AuthenticatedDashboardBuyerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/audit-log': {
      id: '/_authenticated/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof AuthenticatedDashboardAuditLogRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/auction': {
      id: '/_authenticated/dashboard/auction'
      path: '/auction'
      fullPath: '/dashboard/auction'
      preLoaderRoute: typeof AuthenticatedDashboardAuctionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/articles/': {
      id: '/_authenticated/dashboard/articles/'
      path: '/articles'
      fullPath: '/dashboard/articles/'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/webhooks/payos': {
      id: '/api/public/webhooks/payos'
      path: '/public/webhooks/payos'
      fullPath: '/api/public/webhooks/payos'
      preLoaderRoute: typeof ApiPublicWebhooksPayosRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/hooks/priority-recalculate': {
      id: '/api/public/hooks/priority-recalculate'
      path: '/public/hooks/priority-recalculate'
      fullPath: '/api/public/hooks/priority-recalculate'
      preLoaderRoute: typeof ApiPublicHooksPriorityRecalculateRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/hooks/expire-subscriptions': {
      id: '/api/public/hooks/expire-subscriptions'
      path: '/public/hooks/expire-subscriptions'
      fullPath: '/api/public/hooks/expire-subscriptions'
      preLoaderRoute: typeof ApiPublicHooksExpireSubscriptionsRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/admin/leads': {
      id: '/api/public/admin/leads'
      path: '/public/admin/leads'
      fullPath: '/api/public/admin/leads'
      preLoaderRoute: typeof ApiPublicAdminLeadsRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/admin/categories': {
      id: '/api/public/admin/categories'
      path: '/public/admin/categories'
      fullPath: '/api/public/admin/categories'
      preLoaderRoute: typeof ApiPublicAdminCategoriesRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/admin/articles': {
      id: '/api/public/admin/articles'
      path: '/public/admin/articles'
      fullPath: '/api/public/admin/articles'
      preLoaderRoute: typeof ApiPublicAdminArticlesRouteImport
      parentRoute: typeof ApiRoute
    }
    '/_authenticated/dashboard/integrations/hermes': {
      id: '/_authenticated/dashboard/integrations/hermes'
      path: '/integrations/hermes'
      fullPath: '/dashboard/integrations/hermes'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsHermesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/articles/new': {
      id: '/_authenticated/dashboard/articles/new'
      path: '/articles/new'
      fullPath: '/dashboard/articles/new'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/zones': {
      id: '/_authenticated/dashboard/admin/zones'
      path: '/admin/zones'
      fullPath: '/dashboard/admin/zones'
      preLoaderRoute: typeof AuthenticatedDashboardAdminZonesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/import': {
      id: '/_authenticated/dashboard/admin/import'
      path: '/admin/import'
      fullPath: '/dashboard/admin/import'
      preLoaderRoute: typeof AuthenticatedDashboardAdminImportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/edit': {
      id: '/_authenticated/dashboard/admin/edit'
      path: '/admin/edit'
      fullPath: '/dashboard/admin/edit'
      preLoaderRoute: typeof AuthenticatedDashboardAdminEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/companies': {
      id: '/_authenticated/dashboard/admin/companies'
      path: '/admin/companies'
      fullPath: '/dashboard/admin/companies'
      preLoaderRoute: typeof AuthenticatedDashboardAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/claims': {
      id: '/_authenticated/dashboard/admin/claims'
      path: '/admin/claims'
      fullPath: '/dashboard/admin/claims'
      preLoaderRoute: typeof AuthenticatedDashboardAdminClaimsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/admin/companies/batch': {
      id: '/api/public/admin/companies/batch'
      path: '/public/admin/companies/batch'
      fullPath: '/api/public/admin/companies/batch'
      preLoaderRoute: typeof ApiPublicAdminCompaniesBatchRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/admin/articles/$id': {
      id: '/api/public/admin/articles/$id'
      path: '/$id'
      fullPath: '/api/public/admin/articles/$id'
      preLoaderRoute: typeof ApiPublicAdminArticlesIdRouteImport
      parentRoute: typeof ApiPublicAdminArticlesRoute
    }
    '/api/public/admin/analytics/summary': {
      id: '/api/public/admin/analytics/summary'
      path: '/public/admin/analytics/summary'
      fullPath: '/api/public/admin/analytics/summary'
      preLoaderRoute: typeof ApiPublicAdminAnalyticsSummaryRouteImport
      parentRoute: typeof ApiRoute
    }
    '/_authenticated/dashboard/articles/$id/edit': {
      id: '/_authenticated/dashboard/articles/$id/edit'
      path: '/articles/$id/edit'
      fullPath: '/dashboard/articles/$id/edit'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/admin/articles/$id/publish': {
      id: '/api/public/admin/articles/$id/publish'
      path: '/publish'
      fullPath: '/api/public/admin/articles/$id/publish'
      preLoaderRoute: typeof ApiPublicAdminArticlesIdPublishRouteImport
      parentRoute: typeof ApiPublicAdminArticlesIdRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardAuctionRoute: typeof AuthenticatedDashboardAuctionRoute
  AuthenticatedDashboardAuditLogRoute: typeof AuthenticatedDashboardAuditLogRoute
  AuthenticatedDashboardBuyerRoute: typeof AuthenticatedDashboardBuyerRoute
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardMyCompaniesRoute: typeof AuthenticatedDashboardMyCompaniesRoute
  AuthenticatedDashboardOwnerRoute: typeof AuthenticatedDashboardOwnerRoute
  AuthenticatedDashboardSubmitCompanyRoute: typeof AuthenticatedDashboardSubmitCompanyRoute
  AuthenticatedDashboardSubscriptionsRoute: typeof AuthenticatedDashboardSubscriptionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminClaimsRoute: typeof AuthenticatedDashboardAdminClaimsRoute
  AuthenticatedDashboardAdminCompaniesRoute: typeof AuthenticatedDashboardAdminCompaniesRoute
  AuthenticatedDashboardAdminEditRoute: typeof AuthenticatedDashboardAdminEditRoute
  AuthenticatedDashboardAdminImportRoute: typeof AuthenticatedDashboardAdminImportRoute
  AuthenticatedDashboardAdminZonesRoute: typeof AuthenticatedDashboardAdminZonesRoute
  AuthenticatedDashboardArticlesNewRoute: typeof AuthenticatedDashboardArticlesNewRoute
  AuthenticatedDashboardIntegrationsHermesRoute: typeof AuthenticatedDashboardIntegrationsHermesRoute
  AuthenticatedDashboardArticlesIndexRoute: typeof AuthenticatedDashboardArticlesIndexRoute
  AuthenticatedDashboardArticlesIdEditRoute: typeof AuthenticatedDashboardArticlesIdEditRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardAuctionRoute: AuthenticatedDashboardAuctionRoute,
    AuthenticatedDashboardAuditLogRoute: AuthenticatedDashboardAuditLogRoute,
    AuthenticatedDashboardBuyerRoute: AuthenticatedDashboardBuyerRoute,
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardMyCompaniesRoute:
      AuthenticatedDashboardMyCompaniesRoute,
    AuthenticatedDashboardOwnerRoute: AuthenticatedDashboardOwnerRoute,
    AuthenticatedDashboardSubmitCompanyRoute:
      AuthenticatedDashboardSubmitCompanyRoute,
    AuthenticatedDashboardSubscriptionsRoute:
      AuthenticatedDashboardSubscriptionsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAdminClaimsRoute:
      AuthenticatedDashboardAdminClaimsRoute,
    AuthenticatedDashboardAdminCompaniesRoute:
      AuthenticatedDashboardAdminCompaniesRoute,
    AuthenticatedDashboardAdminEditRoute: AuthenticatedDashboardAdminEditRoute,
    AuthenticatedDashboardAdminImportRoute:
      AuthenticatedDashboardAdminImportRoute,
    AuthenticatedDashboardAdminZonesRoute:
      AuthenticatedDashboardAdminZonesRoute,
    AuthenticatedDashboardArticlesNewRoute:
      AuthenticatedDashboardArticlesNewRoute,
    AuthenticatedDashboardIntegrationsHermesRoute:
      AuthenticatedDashboardIntegrationsHermesRoute,
    AuthenticatedDashboardArticlesIndexRoute:
      AuthenticatedDashboardArticlesIndexRoute,
    AuthenticatedDashboardArticlesIdEditRoute:
      AuthenticatedDashboardArticlesIdEditRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicAdminArticlesIdRouteChildren {
  ApiPublicAdminArticlesIdPublishRoute: typeof ApiPublicAdminArticlesIdPublishRoute
}

const ApiPublicAdminArticlesIdRouteChildren: ApiPublicAdminArticlesIdRouteChildren =
  {
    ApiPublicAdminArticlesIdPublishRoute: ApiPublicAdminArticlesIdPublishRoute,
  }

const ApiPublicAdminArticlesIdRouteWithChildren =
  ApiPublicAdminArticlesIdRoute._addFileChildren(
    ApiPublicAdminArticlesIdRouteChildren,
  )

interface ApiPublicAdminArticlesRouteChildren {
  ApiPublicAdminArticlesIdRoute: typeof ApiPublicAdminArticlesIdRouteWithChildren
}

const ApiPublicAdminArticlesRouteChildren: ApiPublicAdminArticlesRouteChildren =
  {
    ApiPublicAdminArticlesIdRoute: ApiPublicAdminArticlesIdRouteWithChildren,
  }

const ApiPublicAdminArticlesRouteWithChildren =
  ApiPublicAdminArticlesRoute._addFileChildren(
    ApiPublicAdminArticlesRouteChildren,
  )

interface ApiRouteChildren {
  ApiPublicAdminArticlesRoute: typeof ApiPublicAdminArticlesRouteWithChildren
  ApiPublicAdminCategoriesRoute: typeof ApiPublicAdminCategoriesRoute
  ApiPublicAdminLeadsRoute: typeof ApiPublicAdminLeadsRoute
  ApiPublicHooksExpireSubscriptionsRoute: typeof ApiPublicHooksExpireSubscriptionsRoute
  ApiPublicHooksPriorityRecalculateRoute: typeof ApiPublicHooksPriorityRecalculateRoute
  ApiPublicWebhooksPayosRoute: typeof ApiPublicWebhooksPayosRoute
  ApiPublicAdminAnalyticsSummaryRoute: typeof ApiPublicAdminAnalyticsSummaryRoute
  ApiPublicAdminCompaniesBatchRoute: typeof ApiPublicAdminCompaniesBatchRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiPublicAdminArticlesRoute: ApiPublicAdminArticlesRouteWithChildren,
  ApiPublicAdminCategoriesRoute: ApiPublicAdminCategoriesRoute,
  ApiPublicAdminLeadsRoute: ApiPublicAdminLeadsRoute,
  ApiPublicHooksExpireSubscriptionsRoute:
    ApiPublicHooksExpireSubscriptionsRoute,
  ApiPublicHooksPriorityRecalculateRoute:
    ApiPublicHooksPriorityRecalculateRoute,
  ApiPublicWebhooksPayosRoute: ApiPublicWebhooksPayosRoute,
  ApiPublicAdminAnalyticsSummaryRoute: ApiPublicAdminAnalyticsSummaryRoute,
  ApiPublicAdminCompaniesBatchRoute: ApiPublicAdminCompaniesBatchRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiRoute: ApiRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapCompaniesDotxmlRoute: SitemapCompaniesDotxmlRoute,
  SitemapIndustriesDotxmlRoute: SitemapIndustriesDotxmlRoute,
  SitemapProvincesDotxmlRoute: SitemapProvincesDotxmlRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapZonesDotxmlRoute: SitemapZonesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompanySlugRoute: CompanySlugRoute,
  CumCongNghiepSlugRoute: CumCongNghiepSlugRoute,
  IndustrySlugRoute: IndustrySlugRoute,
  KhuCongNghiepSlugRoute: KhuCongNghiepSlugRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProvinceSlugRoute: ProvinceSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  CumCongNghiepIndexRoute: CumCongNghiepIndexRoute,
  KcnCcnIndexRoute: KcnCcnIndexRoute,
  KhuCongNghiepIndexRoute: KhuCongNghiepIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
